service: sls-pos

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - ordersTable
          - Arn

package:
  individually: true
  exclude:
    - '**'

plugins:
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-offline # serverless-offline needs to be last in the list

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  hello:
    handler: hello/handler.hello
    layers:
      - ${cf:pos-deps-dev.DepsLayerExport}
    events:
      - httpApi: POST /hello
    package:
      include:
        - hello/**
  order:
    handler: order/handler.writeToDynamo
    events:
      - httpApi: POST /orders
    package:
      include:
        - order/**

resources: # CloudFormation template syntax from here on.
  Resources:
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: orderID
            AttributeType: N
        KeySchema:
          - AttributeName: orderID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
