service: sls-pos

provider:
  name: aws
  runtime: python3.6

package:
  individually: true

plugins:
  - serverless-python-requirements

functions:
  hello:
    handler: handler.hello
    module: hello
    layers:
      - ${cf:pos-deps-dev.DepsLayerExport}
    events:
      - httpApi: POST /hello
  order:
    handler: handler.writeToDynamo
    module: order
    events:
      - httpApi: POST /orders
