** Instructions for using the adapter

1) Create a virtual environment (optional)
   #+begin_src: sh
   sudo apt-get install python-virtualenv
   mkdir myproject
   cd myproject
   python3 -m venv venv      # create venv
   . venv/bin/activate       # activate venv
   #+end_src

2) Install module and dependencies
   #+begin_src sh
   pip install -e $POS_PATH
   #+end_src

3) Put files into myproject folder. Files include configuration.txt, protocol.txt, adapter.py and any agents that are to be tested.

4) Download and install sqlite3
    #+begin_src sh
    sudo apt-get install sqlite3
    #+end_src

5) Download and install browser for managing databases in sqlite3.
    #+begin_src sh
    sudo add-apt-repository -y ppa:linuxgndu/sqlitebrowser
    sudo apt-get update
    sudo apt-get install sqlitebrowser
    #+end_src

6) Search your machine for the installed DB Browser and launch it. You can search it as “DB Browser for SQLite”. Then click “New Database” and specify where you are going to store this Database file. Remember the path to you Database file.

7) Go into your agent’s implementation and update the path to files “configuration.txt” and “protocol.txt” if they are NOT in the same folder as python files.

8) Run the agent
   #+begin_src sh
   python merchant-pos.py
   #+end_src

The agent will automatically run with the host and port specified for its role in configuration.txt
