service: sls-purchase

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage,'dev'}
  environment:
    IS_OFFLINE: ${self:custom.isOffline.${self:provider.stage}}
    CONFIG: ${self:custom.config.${self:provider.stage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:ListStreams
      Resource:
        - Fn::GetAtt:
          - buyerHistory
          - Arn
        - Fn::GetAtt:
          - sellerHistory
          - Arn
        - Fn::GetAtt:
          - ordersTable
          - Arn
        - Fn::GetAtt:
          - offersTable
          - Arn

package:
  individually: true
  exclude:
    - '**'

plugins:
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-offline # serverless-offline needs to be last in the list

custom:
  stages:
    - dev
    - local
  isOffline:
    dev: False
    local: True
  config:
    dev: configuration-dev.yml
    local: configuration-local.yml
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  buyer:
    handler: buyer/buyer.lambda_handler
    events:
      - httpApi: POST /buyer/messages
    package:
      include:
        - buyer/**
        - purchase.json
        - configuration-${self:provider.stage}.yml
    layers:
      - ${cf:pos-adapter-dev.DepsLayerExport}
      - ${cf:pos-adapter-dev.AdapterLayerExport}

  order_trigger:
    handler: buyer/buyer.handle_order
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ordersTable, StreamArn]
    package:
      include:
        - buyer/**
        - purchase.json
        - configuration-${self:provider.stage}.yml
    layers:
      - ${cf:pos-adapter-dev.DepsLayerExport}
      - ${cf:pos-adapter-dev.AdapterLayerExport}
  offer_trigger:
    handler: seller/seller.handle_offer
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [offersTable, StreamArn]
    package:
      include:
        - seller/**
        - purchase.json
        - configuration-${self:provider.stage}.yml
    layers:
      - ${cf:pos-adapter-dev.DepsLayerExport}
      - ${cf:pos-adapter-dev.AdapterLayerExport}
  seller:
    handler: seller/seller.lambda_handler
    events:
      - httpApi: POST /seller/messages
    package:
      include:
        - seller/**
        - purchase.json
        - configuration-${self:provider.stage}.yml
    layers:
      - ${cf:pos-adapter-dev.DepsLayerExport}
      - ${cf:pos-adapter-dev.AdapterLayerExport}

resources: # CloudFormation template syntax from here on.
  Resources:
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: purchaseOrders
        AttributeDefinitions:
          - AttributeName: orderID
            AttributeType: S
        KeySchema:
          - AttributeName: orderID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    offersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: purchaseOffers
        AttributeDefinitions:
          - AttributeName: offerID
            AttributeType: S
        KeySchema:
          - AttributeName: offerID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    buyerHistory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BuyerHistory
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: _time
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
          - AttributeName: _time
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    sellerHistory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SellerHistory
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: _time
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
          - AttributeName: _time
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
